app/views/colleges/__init__.py
from flask import Blueprint

college = Blueprint('college', __name__)

from . import routes

app/views/colleges/routes.py
from . import college
from flask import Flask, render_template, url_for, flash, request, redirect
from app import mysql



#********** College **********


@college.route("/colleges")
def colleges():
    cur = mysql.connection.cursor()
    cur.execute("SELECT  * FROM colleges")
    data = cur.fetchall()
    cur.close()
    return render_template('colleges.html', colleges=data)

@college.route('/college',methods=['POST','GET'])
def colleg():
    code = request.form['code']
    college = request.form['college']
    cur = mysql.connection.cursor()
    check = [code]
    count = cur.execute('select * from colleges where college_code=%s', check)

    if not code or not college:
        flash("All fields required", "error")
        return redirect(url_for('colleges'))

    if count == 0:
        if request.method == "POST":
            flash("Data Successfully Added", "success")
            cur = mysql.connection.cursor()
            cur.execute("INSERT INTO colleges (college_code, college) VALUES (%s, %s)", (code, college))
            mysql.connection.commit()
            return redirect(url_for('college.colleges'))
    else:
        flash("College Already Exist", "error")
        return redirect(url_for('college.colleges'))

@college.route('/delete_college/<string:collegeid>', methods = ['POST', 'GET'])
def delete_college(collegeid):
    cur = mysql.connection.cursor()
    cur.execute("DELETE FROM colleges WHERE collegeid=%s", (collegeid,))
    mysql.connection.commit()
    flash("Record Has Been Deleted Successfully", "success")
    return redirect(url_for('college.colleges'))

@college.route('/update_college',methods=['POST','GET'])
def update_college():
    college_id = request.form['id']
    code = request.form['code']
    college = request.form['college']
    cur = mysql.connection.cursor()
    check = [code]
    count = cur.execute('select * from colleges where college_code=%s', check)

    if request.method == 'POST':
        cur = mysql.connection.cursor()
        cur.execute("""
            UPDATE colleges
            SET college_code=%s, college=%s
            WHERE collegeid=%s
            """, (code, college, college_id))
        mysql.connection.commit()
        flash("Data Updated Successfully", "success")
        return redirect(url_for('college.colleges'))

@college.route('/searchcollege', methods=['GET', 'POST'])
def searchcollege():
    field = request.form.get('college')
    user_input = request.form['searchInput']
    cur = mysql.connection.cursor()
    cur.execute("SELECT  * FROM colleges")
    colleges = cur.fetchall()
    keyword = user_input.upper()
    result = []
    
    if field == 'college':
        for college in colleges:    
            college_allcaps = [str(info).upper() for info in college]
            if keyword in college_allcaps[2]:
                result.append(college)
            result
    else:
        for college in colleges:    
            college_allcaps = [str(info).upper() for info in college]
            if keyword in college_allcaps[1]:
                result.append(college)
            result

    if not user_input or not field:
            flash("Please Input Search Data", "error")


    if len(result) !=0:
        return render_template('colleges.html', colleges=result)
    else:
        return redirect(url_for('college.colleges'))

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font CSS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" ></script>
    <title> {% block title %} {% endblock %}</title>
  </head>
  
<body>

    {% include 'navbar.html' %}
    
  <section class="main">
    <div class="container pb-4">
        <div class="row">
            <div class="col">
                <span>Student Information System</span>
            </div>
        </div>
        
    </div>

    
    <div class="container pb-4">
    <div class="row ">
        <div class="col-2">
          {% block con %} {% endblock %}
        </div>
        <div class="col">
          <button class="btn btn-outline-secondary" type="submit" form="submitbtn">Search</button> 
        </div>
        <div class="col-auto">
          <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">{% block add %} {% endblock %}</button>
        </div>

{% with messages = get_flashed_messages(with_categories=true) %}
  {%if messages%}
    {% for category, message in messages %}
    
    {% if category == 'success' %}
      <div id="flash" class="alert alert-success alert-dismissable fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label ="close">
        </button>
      </div>
    {%endif%}

    {% if category == 'error' %}
      <div id="flashE" class="alert alert-danger alert-dismissable fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label ="close">
        </button>
      </div>
      {%endif%}

    {%endfor%}
  {%endif%}
{%endwith%}

        <!-- Modal -->
        {% block modal %} 

        {% block head %}  {% endblock %}
        
        {% endblock %}

        {% block editmodal %} 
        
        {% endblock %} 

    </div>
    </div>

{% block content %}

{% endblock %}
  
 

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous">

  </script>
 <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
</body>

<footer>
  <h1>Copyright © 2021 JedWeb. </h1>
</footer>
</section>
</html> 

app/templates/colleges.html
{% extends 'base.html' %}

{% block title %} Colleges {% endblock %}

{% block con %}
<form id="submitbtn" action="/searchcollege" method="POST" class="form-inline">
  
 <input type="text" class="form-control" name="searchInput" id="searchInput" placeholder="Search College" aria-label="State"> 
  
 <div class="form-group">
  <div class="input-group mt-3" > 
    <select class="custom-select" id="college" name="college">
      <option disabled selected="">Select Field</option>
      <option value="0">College Code</option>
      <option value="college">College</option>
    </select>
  </div>
</div>

</form>


 {% endblock %}

{% block add %} Add New {% endblock %}

{% block modal %} 
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">  
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% block head %} Add Course {% endblock %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('college.colleg') }}" method="POST">

          <div class="form-group">
             <label>College Code:</label>
              <input type="text" class="form-control" name="code" value="">
          </div>

          <div class="form-group">
             <label>College:</label>

             <input type="text" class="form-control" name="college" value="">
          </div> 
          <br />

          <div class="form-group">
            <button class="btn btn-success" type="submit" >Save changes</button>
          </div>

       </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block editmodal %} 
{% for row in colleges%}
<div class="modal fade" id="modaledit{{row.0}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">  
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('college.update_college') }}" method="POST">

          <div class="form-group">
             <label>College Code:</label>
              <input type="hidden"  name="id" value="{{row.0}}"> 
              <input type="text" class="form-control" name="code" value="{{row.1}}">
          </div>

          <div class="form-group">
            <label>College:</label>

            <input type="text" class="form-control" name="college" value="{{row.2}}">
         </div>
         
          <br />

          <div class="form-group">
            <button class="btn btn-success" type="submit" >Save changes</button>
          </div>

       </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
{% endfor  %}
        
{% endblock %} 

{% block content %}
<section class="content">
        <div class="container pb-3">
        <table class="table sticky text-center">
            <thead>
              <tr>
                <th scope="col">College Code</th>
                <th scope="col">College</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
    
            <tbody>
                {% for row in colleges %}
              <tr>
                <td>{{row.1}}</td>
                <td>{{row.2}}</td>
                <td>
                  <a href="" data-bs-toggle="modal" data-bs-target="#modaledit{{row.0}}" class="btn btn-warning btn-sm" ><i class="bi bi-pencil-square"></i></a>
                  <a href="/delete_college/{{ row.0 }}" class="btn btn-danger btn-sm" onclick= "return confrim('Are You Sure To Delete?')"><i class="bi bi-trash"></i></a>
                </td>
              </tr>
              {% endfor  %}
            </tbody>
          </table>
        </div>
    
    </section>


{% endblock %}

app/templates/courses.html
{% extends 'base.html' %}

{% block title %} Courses {% endblock %}

{% block con %}
<form id="submitbtn" action="/searchcourse" method="POST" class="form-inline">
 <input type="text" class="form-control" name="searchInput" id="searchInput" placeholder="Search Courses" aria-label="State"> 

 <div class="form-group">
  <div class="input-group mt-3" > 
    <select class="custom-select" id="course" name="course">
      <option disabled selected="">Select Field</option>
      <option value="0">Course Code</option>
      <option value="1">Course</option>
      <option value="2">College</option>
    </select>
  </div>
</div>

</form>
 {% endblock %}

{% block add %} Add New {% endblock %}

{% block modal %} 
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">  
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% block head %} Add Course {% endblock %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('course.cours') }}" method="POST">

          <div class="form-group">
             <label>Course Code:</label>
              <input type="text" class="form-control" name="code" value="">
          </div>

          <div class="form-group">
             <label>Course:</label>

             <input type="text" class="form-control" name="course" value="">
          </div> 

          <div class="form-group">
            College:
            <div class="input-group mb-3" > 
              <select class="custom-select" id="college" name="college" value="">
                <option selected="">Select a College</option>
                {% for co in col %}
                <option>{{co.1}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <br />

          <div class="form-group">
            <button class="btn btn-success" type="submit" >Save changes</button>
          </div>

       </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

{% endblock %}


{% block editmodal %} 
{% for row in courses%}
<div class="modal fade" id="modaledit{{row.0}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">  
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('course.update_course') }}" method="POST">

          <div class="form-group">
             <label>Course Code:</label>
              <input type="hidden"  name="id" value="{{row.0}}"> 
              <input type="text" class="form-control" name="code" value="{{row.1}}">
          </div>

          <div class="form-group">
             <label>Course:</label>

             <input type="text" class="form-control" name="course" value="{{row.2}}">
          </div> 

         <div class="form-group">
          College:
          <div class="input-group mb-3" >   
            <select class="custom-select" name="college" >
              <option disabled>{{row.3}}</option>
              {% for co in col %}
              <option>{{co.1}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
         
          <br />

          <div class="form-group">
            <button class="btn btn-success" type="submit" >Save changes</button>
          </div>

       </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
{% endfor  %}
        
{% endblock %} 

{% block content %}
<section class="content">
        <div class="container pb-3 scrollable">
        <table class="table sticky text-center">
            <thead>
              <tr>
                <th scope="col">Course Code</th>
                <th scope="col">Course</th>
                <th scope="col">College</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
    
            <tbody>
                {% for row in courses %}
              <tr>
                <td>{{row.1}}</td>
                <td>{{row.2}}</td>
                <td>{{row.3}}</td>
                <td>
                  <a href="" data-bs-toggle="modal" data-bs-target="#modaledit{{row.0}}" class="btn btn-warning btn-sm" ><i class="bi bi-pencil-square"></i></a>
                    <a href="/delete/{{ row.0 }}" class="btn btn-danger btn-sm" onclick="return confirm('Are You Sure For Delete?')"><i class="bi bi-trash"></i></a>
                </td>
              </tr>
              {% endfor  %}
            </tbody>
          </table>
        </div>
    
    </section>


{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %} SSIS. {% endblock %}

{% block con %}
<form id="submitbtn" action="/searchstudent" method="POST" class="form-inline">
 <input type="text" class="form-control" name="searchInput" id="searchInput" placeholder="Search Student" aria-label="State"> 
 <div class="form-group">
  <div class="input-group mt-3" > 
    <select class="custom-select" id="student" name="student">
      <option disabled selected="">Select Field</option>
      <option value="0">ID</option>
      <option value="1">First Name</option>
      <option value="2">Last Name</option>
      <option value="3">Course</option>
      <option value="4">Year Level</option>
      <option value="5">Gender</option>
    </select>
  </div>
</div>

</form>
 {% endblock %}

{% block add %} Add New {% endblock %}

{% block modal %} 
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">  
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% block head %} Add Students {% endblock %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('student.home') }}" enctype = "multipart/form-data" method="POST">
          {{form.hidden_tag()}}
          <div class="form-group">
             <label>ID:</label>
              <input type="text" class="form-control" name="id" value="">
          </div>
          
          <div class="form-group mt-3">
            <p>Photo:{{form.profile()}}</p>
          </div>

          <div class="form-group">
             <label>First Name:</label>
             <input type="text" class="form-control" name="first" value="">
          </div>

          <div class="form-group">
             <label>Last Name:</label>
             <input type="text" class="form-control" name="last" value="">
          </div>

          <div class="form-group">
            Course:
            <div class="input-group mb-3" > 
              <select class="custom-select" id="course" name="course" type="text" required>
                <option selected="">Select a Course</option>
                {% for col in college %}
                <optgroup label="{{col.1}}">
                {% for co in cor %}
                {% if co.3 == col.1%}
                <option>{{co.1}}</option>
                {%endif%}
                {% endfor %}  
              </optgroup>
              {%endfor%}
              </select>
            </div>
          </div>
          
          <div class="form-group">
            Year Level:
            <div class="input-group mb-3" > 
              <select class="custom-select" id="level" name="year" required>
                <option disabled selected="">Select Year Level</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>
          </div>

          <div class="form-group">
            Gender:
            <div class="input-group mb-3" > 
              <select class="custom-select" id="gender" name="gender" required>
                <option selected="">Select Gender</option>
                <option>M</option>
                <option>F</option>
              </select>
            </div>
          </div>

     <br />
     <div class="form-group">
      <button class="btn save" type="submit" >Save changes</button>
     </div>

       </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block editmodal %} 
{% for row in students %}
<div class="modal fade" id="modaledit{{row.0}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">  
    <div class="modal-content">
      <div class="modal-body">
        <form action="{{ url_for('student.update_student') }}" enctype = "multipart/form-data" method="POST">
          {{form.hidden_tag()}}
          <div class="form-group">
             <label>ID:</label>
              <input type="hidden"  name="studid" value="{{row.0}}"> 
              <input type="text" class="form-control" name="id" value="{{row.1}}">
          </div>
          <div class="form-group mt-3">
            <p>Photo:{{form.profile()}}</p>
          </div>

          <div class="form-group">
             <label>First Name:</label>
             <input type="text" class="form-control" name="first" value="{{row.2}}">
          </div>


          <div class="form-group">
             <label>Last Name:</label>
             <input type="text" class="form-control" name="last" value="{{row.3}}">
          </div>

          <div class="form-group">
            Course:
            <div class="input-group mb-3" > 
              <select class="custom-select" name="course" required>
                <option disabled>{{row.4}}</option>
                {% for col in college %}
                <optgroup label="{{col.1}}">
                {% for co in cor %}
                {% if co.3 == col.1%}
                <option>{{co.1}}</option>
                {%endif%}
                {% endfor %}  
              </optgroup>
              {%endfor%}
              </select>
            </div>
          </div>
         
          <div class="form-group">
            Year Level:
            <div class="input-group mb-3" > 
              <select class="custom-select" name="year" required>
                <option disabled>{{row.5}}</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>
          </div>

       <div class="form-group">
        Gender:
        <div class="input-group mb-3" > 
          <select class="custom-select" name="gender" required>
            <option disabled >{{row.6}}</option>
            <option>M</option>
            <option>F</option>
          </select>
        </div>
      </div>

     <br />
     <div class="form-group">
      <button class="btn save" type="submit" >Save changes</button>
     </div>

       </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endfor  %}
        
{% endblock %} 

{% block content %}

<section class="content">
  <div class="row">
    <div class="col">
    <div class="container pb-3 scrollable">
    <table class="table sticky text-center">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Photo</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Course</th>
            <th scope="col">Year Level</th>
            <th scope="col">Gender</th>
            <th scope="col">Action</th>
          </tr>
        </thead>

        <tbody>
          {% for row in students %}
          <tr>
            <td>{{row.1}}</td>
            <td><img src ='{{row.7}}'> </td>
            <td>{{row.2}}</td>
            <td>{{row.3}}</td>
            <td>{{row.4}}</td>
            <td>{{row.5}}</td>
            <td>{{row.6}}</td>
            <td>
              <a href="" data-bs-toggle="modal" data-bs-target="#modaledit{{row.0}}" class="btn btn-warning btn-sm" ><i class="bi bi-pencil-square"></i></a>
              <a href="/delete_stud/{{ row.1 }}" class="btn btn-danger btn-sm" onclick="return confirm('Are You Sure For Delete?')"><i class="bi bi-trash"></i></a>
            </td>
          </tr>
          {% endfor  %}
        </tbody>
      </table>
    </div>
  </div>
  </div>
</section>

{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand"><img src="/static/img/SSIS..png" alt="logo"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ms-auto">
        <a  href="{{ url_for('student.home') }}">STUDENTS</a>
        <a  href="{{ url_for('course.courses') }}">COURSES</a>
        <a  href="{{ url_for('college.colleges') }}">COLLEGES</a>
      </div>
      <script type="text/javascript">
        const currentLocation = location.href;
        const menuItem = document.querySelectorAll('a');
        const menuLength = menuItem.length
        for (let i = 0; i<menuLength; i++ ){
          if(menuItem[i].href === currentLocation)
            menuItem[i].className = "active"
        }
      
      </script>
    </div>
  </div>
</nav>
